server:
  port: 8080
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/haobi
    username: root
    password: password
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
    password: password
  # rabbitmq配置
  rabbitmq:
    host: mq
    port: 5672
    #    virtual-host: /hmall # 虚拟主机
    username: guest
    password: password
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: password
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''